### ISSUE TITLE
Problem with Button.is_pressed()

### ISSUE THREAD

**Issue by TravelTrader** [noamraph/mindstorms#2]
I am sorry to add an issue here but I really like your tool and I hope to get it run with all possibilities.
Now I found an error by using `is_pressed()`. It is very likely based on my usage.

It doesn't matter if used just by `print(hub.button.left.is_pressed())` or in a loop by `while not hub.button.left.is_pressed():` I am getting this error message:

```
Traceback (most recent call last):
  File "10-counter.py", line 8, in <module>
    print(hub.button.left.is_pressed())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/mindstorms.py", line 412, in is_pressed
    return self._hub._mcall(self._me, 'is_pressed')
  File "/home/ubuntu/.local/lib/python3.8/site-packages/mindstorms.py", line 56, in _mcall
    return self._call(f'{name}.{method}', *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/mindstorms.py", line 53, in _call
    return self._eval(expr)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/mindstorms.py", line 47, in _eval
    b = self._pb.exec_(f'print(repr({expr}))')
  File "/home/ubuntu/.local/lib/python3.8/site-packages/rshell/pyboard.py", line 264, in exec_
    raise PyboardError('exception', ret, ret_err)
rshell.pyboard.PyboardError: ('exception', b'', b'Traceback (most recent call last):\r\n  File "<stdin>", line 1, in <module>\r\nAttributeError: \'module\' object has no attribute \'buttons\'\r\n')
```

I also checked your `mindstorms.py` but couldn't find any mistake. Same problems with `was_pressed()`.

Thank you very much again for your help!
Alexander

**Comment by noamraph** [comment]
Thanks Alexander! That was a real bug. I uploaded version 0.1.1. Can you test it, and re-open the issue if needed?

**Comment by TravelTrader** [comment]
Tested. Works.
Awesome.

Could you explain a little what you changed please?
